#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
sudo apt-get update
sudo apt-get -y install nginx
sudo apt-get -y upgrade

string_for_replacement="server_name _;\n\tadd_header X-Served-By \$hostname"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart