#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script
# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

server_config=\
"
frontend  tariro-frontend
        bind *:80
        mode http
        default_backend tariro-backend
backend tariro-backend
        balance roundrobin
        server 76795-web-01 54.174.125.138 check
        server 76795-web-02 54.175.54.26 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
