#!/usr/bin/env bash
# generates a MySQL dump and creates a compressed archive out of it
sudo mysqldump -u root -p$1 --all-databases >backup.sql
name=$(date +"%d-%m-%Y")
tar -czf $name.tar.gz backup.sql